### ISSUE TITLE
Google colab - `pmg config --add PMG_MAPI_KEY` produces error in `_load_pmg_settings`

### ISSUE THREAD

**Issue by sgbaird** [TRI-AMDD/piro#57]
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/sparks-baird/piro/blob/main/piro/notebooks/BaTiO3-Example-Colab.ipynb)
```python
MP_API_KEY = '' #@param {type:"string"}
!pmg config --add PMG_MAPI_KEY {MP_API_KEY}
```

> ```python
> Traceback (most recent call last):
>   File "/usr/local/bin/pmg", line 5, in <module>
>     from pymatgen.cli.pmg import main
>   File "/usr/local/lib/python3.7/dist-packages/pymatgen/cli/pmg.py", line 15, in <module>
>     from pymatgen.core import SETTINGS
>   File "/usr/local/lib/python3.7/dist-packages/pymatgen/core/__init__.py", line 61, in <module>
>     SETTINGS = _load_pmg_settings()
>   File "/usr/local/lib/python3.7/dist-packages/pymatgen/core/__init__.py", line 51, in _load_pmg_settings
>     d.update(d_yml)
> TypeError: 'NoneType' object is not iterable
> ```

Workaround is to just use `export MAPI_KEY=<your API key>`, but then another error ensues (which appears regardless of using Google Colab or not). See #58

**Comment by sgbaird** [comment]
I think I've got it figured out, and it will be addressed in the next `pymatgen` release. Workaround is to delete `.pmgrc.yaml` if it's an empty file and make sure not to use the `pmg --add` CLI, only the shell `export` command.

https://github.com/materialsproject/pymatgen/issues/2377
